### PR TITLE
Add support for rangemappingtable to handle non contiguous ranges (#5)

### LINKED ISSUE #5: Add support for RangeMappingTable to handle non-contiguous ranges
RangeMappingTable throws an error when the cuts are not contiguous

```
RangeMappingTable$new("Test", "test",
                      "Low" = c(-Inf, 5),
                      "Mid" = c(5, 9),  # Error disappears when c(5, 10)
                      "High" = c(10, 15),
                      .other = NULL,
                      .total = "Total")

Error in `dplyr::inner_join()` at modulartabler/R/mapping_table.R:339:6:
! Each row of `x` must have a match in `y`.
ℹ Row 3 of `x` does not have a match.
```
This behaviour is unexpected and doesn't follow the BaseMappingTable ability to selectively map and ignore other values

### PR DESCRIPTION
**Pull request by inpowell**
Solves #5

### CODE REVIEW

**Comment by PeterM74** [comment]
Non-contiguous update working for me. I submitted a small update as it looks like one of the other updates added a warning to `convert_tabular`. Annoyingly this warning is one of the timed warnings that only appears once in a time period (as it disappeared when I ran the test again) so I imagine the warning disappeared when you ran the final tests on the PR. Checks are now passing without warnings.

```
ℹ Testing modulartabler
✔ | F W  S  OK | Context
✔ |          7 | cell_suppression [1.1s]                                                   
✔ |         38 | mapping_table                                                             
✔ |   1      5 | tables_long                                                               
───────────────────────────────────────────────────────────────────────────────────────────
Warning (test-tables_long.R:42:3): convert_tabular converts a semi-long table correctly
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
ℹ Please use `".valname"` instead of `.data$.valname`
Backtrace:
     ▆
  1. └─modulartabler::convert_tabular(...) at test-tables_long.R:42:2
  2.   ├─dplyr::arrange(...) at modulartabler/R/tables_long.R:119:4
  3.   ├─dplyr::select(...)
  4.   └─dplyr:::select.data.frame(...)
  5.     └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
  6.       └─tidyselect:::eval_select_impl(...)
  7.         ├─tidyselect:::with_subscript_errors(...)
  8.         │ └─rlang::try_fetch(...)
  9.         │   └─base::withCallingHandlers(...)
 10.         └─tidyselect:::vars_select_eval(...)
 11.           └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 12.             └─tidyselect:::eval_c(expr, data_mask, context_mask)
 13.               └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 14.                 └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 15.                   └─tidyselect:::expr_kind(expr, context_mask, error_call)
 16.                     └─tidyselect:::call_kind(expr, context_mask, error_call)
───────────────────────────────────────────────────────────────────────────────────────────

══ Results ════════════════════════════════════════════════════════════════════════════════
Duration: 2.6 s

[ FAIL 0 | WARN 1 | SKIP 0 | PASS 50 ]
```

**Review by PeterM74 — APPROVED** [review]
Issue #5 fixed. Added optional fix to warning in `convert_tabular()`

**Comment by inpowell** [comment]
Hmm, unfortunately that change was required to fix an `R CMD check` NOTE -- [this one](https://github.com/inpowell/modulartabler/actions/runs/10468846677/job/28990602836?pr=8#step:6:94)... looks like neither of our solutions has been perfect.

**Comment by PeterM74** [comment]
> Hmm, unfortunately that change was required to fix an `R CMD check` NOTE -- [this one](https://github.com/inpowell/modulartabler/actions/runs/10468846677/job/28990602836?pr=8#step:6:94)... looks like neither of our solutions has been perfect.

Damn, a good reminder to check the check properly! Thanks for catching, happy with this to be merged.

**Pull request merged**
