### PR TITLE
(#12, #22) Return masked vectors from cell suppression functions

### LINKED ISSUE #12: Use maskr
maskr has been released on CRAN - https://cran.r-project.org/package=maskr

### PR DESCRIPTION
**Pull request by inpowell**
This PR introduces the maskr package to modulartabler. Cell suppression functions now return a masked vector that behaves with basic arithmetic and tidyverse (but not data.table) reshaping functions.

This should reduce a bit of overhead when creating tables with counts and percentages.

Implements #12
Solves #22

### CODE REVIEW

**Comment by PeterM74** [comment]
Hi @inpowell! I updated suppress_secondary to correctly check for inheritance as when I mask a vector I got a different class name than what it was checking for (and of course the matrix operations were not happy about receiving a 'vector' it couldn't understand). I was in the process of updating README.Rmd to explicitly use masked vectors (although I imagine the vignette may solve this anyhow in #6), when I realised the example doesn't actually work as it is incorrectly calculating the nullspace for RangeMappingTable (added as issue #22). I have added the README update but currently it won't knit without error due to the nullspace issue. I think we should include a solution for this before merging to ensure the README accurately reflects the updated functionality of the package (but understand if you would rather this were solved in a separate pull request, in which case just revert the last commit).

May need your help to narrow down the root cause of this one 🤔

**Comment by inpowell** [comment]
I had been relying on an undocumented assumption (whoopsie) on `dplyr::cur_group_id()` that it would somehow do some ordering under the hood -- a bit of a hangover from the data.table days when this assumption held true!

Added a unit test and fixed in this PR for simplicity's sake.

**Comment by PeterM74** [comment]
Perfect! I figured you might have some insight into what happened given it was clearly working previously!

**Review by PeterM74 — APPROVED** [review]

**Comment by inpowell** [comment]
Yeah - I'm curious about why it came up, because I was quite sure it worked before! Ah well, fixed now, and thanks for picking up on it and the review

**Pull request merged**
